### ISSUE TITLE
Question on GPIO indexing compared to config-gpio (hdmi audio)

### ISSUE THREAD

**Issue by acourdavault** [mvduin/bbb-pin-utils#1]
Hello

Thank you for what yu ve done.
The program works well i think (tested on 4.1, 4.4, 4.9) on my beaglebone black Wireless.

I found this using the program:
```
audio osc enable                  27 fast    down 7 gpio 1.27 lo >>  clk_mcasp0 (mcasp0_pins)
P9.31 / hdmi audio clk           100 fast    down 0 asp 0 tx clk     mcasp@48038000 (mcasp0_pins)
P9.29 / hdmi audio fs            101 fast     up  0 asp 0 tx fs      mcasp@48038000 (mcasp0_pins)
P9.28 / hdmi audio data          103 fast    down 2 asp 0 data 2     mcasp@48038000 (mcasp0_pins)
P9.25 / audio osc                107 fast rx  up  0 asp 0 tx hclk    mcasp@48038000 (mcasp0_pins)
```
**my question is about the first line.
WHERE is "audio osc enable"?**

I ve found it on the schematics, and the description is rather good.
Now I would want to change this value, and i thought i would use `config-pin` but neither `gpio1.27` nor `gpio1_27` nor 'audio enable osc' work on this.

And I need to set it to HI.

I wanted to know if you had any idea?

also how to get the info with config pins (which shows the overlays using the pin)

Thank you

PS
**also is it possible to know which overlay created this pin?**

**Comment by mvduin** [comment]
As shown in the last column, that pin (and associated gpio) is in use by the kernel device "clk_mcasp0", and therefore cannot be controlled or reconfigured from userspace. The kernel will automatically set the gpio high whenever the clock is requested by the mcasp driver. You should be able to confirm that audio osc enable shows "hi >>" instead of "lo >>" during audio playback.

The "clk_mcasp0" device is declared in the "BB-HDMI-TDA998x" overlay if you are using u-boot overlays (very recent images only), otherwise it is not declared in an overlay but in the main dtb ("am335x-boneblack-wireless" in your case).

**Comment by mvduin** [comment]
Also, your question is not an issue in show-pins, or even related to it at all really.

In the future, please refrain from using github issues as a support forum for the beaglebone, use the [official forums](https://groups.google.com/forum/#!forum/beagleboard) or the IRC chat.

**Comment by acourdavault** [comment]
@mvduin 

Thank you, I thought i could change the value with the name of the pin in show-pins.
I am sorry, thanks again for your help
